### ISSUE TITLE
How to implement the GCR method on a gallery of 50,000 images?

### ISSUE THREAD

**Issue by Ning5195** [WesleyZhang1991/GCN_rerank#1]
Excellent job! 
Can the GCR method implement on a gallery of 50,000 pedestrian images? It seems that the calculation process will take up a lot of memory. 
Thank You!

**Comment by WesleyZhang1991** [comment]
The default config uses GPU argsort for faster speed. If the GPU memory is limited, try with CPU argsort by modifying configs with lower speed, e.g. [WITH_GPU](https://github.com/WesleyZhang1991/GCN_rerank/blob/ff4d269ea43751a1fbb3cb8d8e1db432bdedcce3/config/defaults.py#L38).
