### ISSUE TITLE
Extracted Features Google Drive link is broken

### ISSUE THREAD

**Issue by montonous** [WesleyZhang1991/GCN_rerank#2]
Hi, Thanks for sharing your work!

I want to replicate this method but the link to the features seems to be broken. Could it be replaced?

Thank you for your time

**Comment by WesleyZhang1991** [comment]
It is ok now with the new link https://drive.google.com/drive/folders/13pzDLmdbal2SpVCIaa4yczx7aPJK8yVx?usp=share_link

**Comment by montonous** [comment]
Thanks a lot!
